---
name: Merges

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

env:
  BUILD_CONTEXT: '.'
  DOCKERFILE_PATH: 'Dockerfile'
  IMAGE: hello-world

jobs:
  # Push to Github Packages
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}/${{ env.IMAGE }}
          registry: docker.pkg.github.com
          path: ${{ env.BUILD_CONTEXT }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          tag_with_ref: true
