---
name: Merges

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

env:
  DOCKER_BUILDCONTEXT: '.'
  DOCKER_FILEPATH: 'Dockerfile'
  DOCKER_REPOSITORY: ${{ github.repository }}
  DOCKER_IMAGE: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE }}
          registry: docker.pkg.github.com
          path: ${{ env.DOCKER_BUILDCONTEXT }}
          dockerfile: ${{ env.DOCKER_FILEPATH }}
          tag_with_ref: true
      - name: Save Docker Images
        # TODO replace this with build-push-image tag output once added
        run: |
            docker save \
            docker.pkg.github.com/${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE }}:latest \
              | gzip > container.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          path: container.tar.gz
          name: ${{ env.DOCKER_IMAGE }}
