---
name: Pull Requests

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:

env:
  BUILD_CONTEXT: '.'
  DOCKERFILE_PATH: 'Dockerfile'
  IMAGE: hello-world

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}/${{ env.IMAGE }}
          tag_with_ref: true
          path: ${{ env.BUILD_CONTEXT }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          push: false
  # Push to Github Packges
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}/${{ env.IMAGE }}
          registry: docker.pkg.github.com
          path: ${{ env.BUILD_CONTEXT }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          tag_with_ref: true
  # Push to Dockerhub
  publish:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: bramweltpoc/ci-sample-docker/${{ env.IMAGE }}
          registry: docker.io
          path: ${{ env.BUILD_CONTEXT }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          tag_with_ref: true
