---
name: Releases

# yamllint disable-line rule:truthy
on:
  tags:

env:
  DOCKER_ORG: 'bramwelttest'
  BUILD_CONTEXT: '.'
  DOCKERFILE_PATH: 'Dockerfile'
  IMAGE: hello-world

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ env.DOCKER_ORG }}/${{ env.IMAGE }}
          registry: docker.io
          path: ${{ env.BUILD_CONTEXT }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          tag_with_ref: true
